const units={
  forces:{
    label:"Learning area",title:"Forces & Motion",intro:"How forces change motion, how motion is measured, and how Newton’s laws explain what happens.",pathway:["Forces","Balanced and unbalanced forces","Free-body diagrams","Speed, distance and time","Acceleration","Distance–time graphs","Speed–time graphs","Comparing motion","Work","Newton’s first law","Newton’s second law","Newton’s third law","Motion calculations"],
    lessons:[
      {title:"Forces and free body diagrams",summary:"A force is a push or pull. Free body diagrams show the forces acting on one object.",keywords:["force","contact","non-contact","free body diagram","newton"],body:`
        <div class="lesson-grid"><section class="note-panel"><h3>Core ideas</h3><ul><li>Forces have a size and direction. We measure force in newtons (N).</li><li>Contact forces include friction, drag, normal support and tension.</li><li>Non-contact forces include gravity, magnetic force and electrostatic force.</li><li>A free body diagram uses labelled arrows. A longer arrow represents a larger force.</li></ul><div class="callout"><strong>Diagram rule:</strong> Draw arrows from the object. Label every force and show its direction.</div></section><section class="visual-panel"><h3>Balanced example</h3><div class="force-diagram"><span class="force-arrow left"><small>50 N</small></span><div class="force-block">BOX</div><span class="force-arrow right"><small>50 N</small></span></div><p>Equal forces in opposite directions give a net force of 0 N.</p></section></div>`},
      {title:"Balanced and unbalanced forces",summary:"The net force tells us whether an object’s motion will change.",keywords:["balanced","unbalanced","net force","resultant","direction"],body:`
        <div class="lesson-grid"><section class="note-panel"><h3>Finding net force</h3><ul><li>Forces in the same direction add together.</li><li>Forces in opposite directions subtract.</li><li>Balanced forces give a net force of 0 N. The object stays still or continues at constant velocity.</li><li>An unbalanced net force causes acceleration in the direction of the larger force.</li></ul></section><section class="worked-panel"><h3>Worked example</h3><div class="formula">120 N right − 75 N left = 45 N right</div><ol class="worked-steps"><li>Identify the two directions.</li><li>Subtract the smaller opposing force.</li><li>State both the size and direction.</li></ol></section></div>`},
      {title:"Speed and acceleration",summary:"Speed measures how fast distance changes. Acceleration measures how quickly velocity changes.",keywords:["speed","distance","time","acceleration","velocity"],body:`
        <div class="lesson-grid"><section class="note-panel"><h3>Motion equations</h3><div class="formula">speed = distance ÷ time</div><div class="formula" style="margin-top:10px">acceleration = change in velocity ÷ time</div><ul><li>Speed uses units such as m/s or km/h.</li><li>Acceleration uses m/s².</li><li>Negative acceleration means velocity is decreasing in the chosen positive direction.</li></ul></section><section class="worked-panel"><h3>Try the speed calculator</h3><div class="motion-tool"><label>DISTANCE (m)<input id="distance-input" type="number" min="0" value="100"></label><label>TIME (s)<input id="time-input" type="number" min="0.01" step="0.01" value="12.5"></label><label>SPEED (m/s)<input id="speed-input" type="number" readonly></label><div id="motion-result" class="motion-result">100 ÷ 12.5 = 8 m/s</div></div></section></div>`},
      {title:"Motion graphs",summary:"The gradient of a graph shows how quickly one quantity changes compared with another.",keywords:["distance-time","speed-time","gradient","stationary","constant speed"],body:`
        <div class="lesson-grid"><section class="note-panel"><h3>Distance-time graphs</h3><ul><li>A rising straight line shows constant speed.</li><li>A horizontal line shows the object is stationary.</li><li>A steeper line shows a faster speed.</li><li>A curve that becomes steeper shows acceleration.</li></ul></section><section class="note-panel"><h3>Speed-time graphs</h3><ul><li>A horizontal line above zero shows constant speed.</li><li>An upward slope shows positive acceleration.</li><li>A downward slope shows speed decreasing.</li><li>The gradient equals acceleration.</li></ul></section><section class="worked-panel wide"><h3>Worked gradient</h3><div class="formula">gradient = change in vertical axis ÷ change in horizontal axis</div><p>A runner travels from 0 m to 60 m in 10 s. The gradient is 60 ÷ 10 = <strong>6 m/s</strong>.</p></section></div>`},
      {title:"Work in physics",summary:"Work happens when a force moves an object through a distance.",keywords:["work","force","distance","joule","energy"],body:`
        <div class="lesson-grid"><section class="note-panel"><h3>Work and energy</h3><div class="formula">work = force × distance</div><ul><li>Work is measured in joules (J).</li><li>The force must cause movement in its direction.</li><li>No movement means no mechanical work has been done on the object.</li><li>Doing work transfers energy.</li></ul></section><section class="worked-panel"><h3>Worked example</h3><p>A student pushes a trolley with a force of 40 N for 6 m.</p><div class="formula">W = 40 × 6 = 240 J</div><div class="callout"><strong>Always include units.</strong> Force in N and distance in m give work in J.</div></section></div>`},
      {title:"Newton’s three laws",summary:"Newton’s laws connect forces, mass and changes in motion.",keywords:["inertia","F = ma","action-reaction","mass","acceleration"],body:`
        <div class="lesson-grid"><section class="note-panel"><h3>First law: inertia</h3><p>An object remains at rest or continues at constant velocity unless a net force acts on it. More mass means more inertia.</p></section><section class="note-panel"><h3>Second law: F = ma</h3><p>Acceleration increases when net force increases. For the same force, an object with more mass accelerates less.</p><div class="formula">net force = mass × acceleration</div></section><section class="note-panel"><h3>Third law: force pairs</h3><p>When object A pushes object B, object B pushes object A with an equal force in the opposite direction. The forces act on different objects.</p></section><section class="key-panel"><h3>Common trap</h3><p>Balanced forces act on the same object. A Newton’s third law pair acts on two different objects.</p></section></div>`}
    ]
  },
  chemistry:{
    label:"Learning area",title:"Chemistry",intro:"What matter is made from, how the periodic table is organised, and how substances react or separate.",pathway:["Matter and particles","States and phase change","Atoms and subatomic particles","Elements, compounds and mixtures","Periodic table","Electron shells for the first 20 elements","Atoms and ions","Acids, bases and pH","Acid reactions","Separating mixtures"],
    lessons:[
      {title:"Matter, particles and states",summary:"Matter has mass and takes up space. Particle movement and spacing explain solids, liquids and gases.",keywords:["matter","particle","mass","volume","solid","liquid","gas"],body:`
        <div class="lesson-grid"><section class="note-panel"><h3>Matter and particles</h3><ul><li>Matter is anything that has mass and takes up space.</li><li>In a solid, particles vibrate in fixed positions.</li><li>In a liquid, particles remain close but move past each other.</li><li>In a gas, particles are far apart and move freely.</li><li>Heating increases particle kinetic energy.</li></ul></section><section class="visual-panel"><h3>Particle model</h3><div class="particle-boxes"><div class="particle-state"><b>SOLID</b><div class="dots">${'<i></i>'.repeat(12)}</div></div><div class="particle-state liquid"><b>LIQUID</b><div class="dots">${'<i></i>'.repeat(12)}</div></div><div class="particle-state gas"><b>GAS</b><div class="dots">${'<i></i>'.repeat(9)}</div></div></div></section><section class="worked-panel wide"><h3>Changes of state</h3><table class="mini-table"><tr><th>CHANGE</th><th>FROM</th><th>TO</th></tr><tr><td>Melting</td><td>Solid</td><td>Liquid</td></tr><tr><td>Freezing</td><td>Liquid</td><td>Solid</td></tr><tr><td>Evaporation / boiling</td><td>Liquid</td><td>Gas</td></tr><tr><td>Condensation</td><td>Gas</td><td>Liquid</td></tr></table></section></div>`},
      {title:"Atoms, ions and electron shells",summary:"Atoms contain protons, neutrons and electrons. Electron arrangements explain how atoms form ions.",keywords:["atom","nucleus","proton","neutron","electron","shell","ion"],body:`
        <div class="lesson-grid"><section class="note-panel"><h3>Parts of an atom</h3><table class="mini-table"><tr><th>PARTICLE</th><th>CHARGE</th><th>LOCATION</th></tr><tr><td>Proton</td><td>+1</td><td>Nucleus</td></tr><tr><td>Neutron</td><td>0</td><td>Nucleus</td></tr><tr><td>Electron</td><td>−1</td><td>Electron shells</td></tr></table><div class="callout"><strong>Neutral atom:</strong> number of protons = number of electrons.</div></section><section class="key-panel"><h3>Atomic number, shells and ions</h3><ul><li>Atomic number = number of protons.</li><li>Mass number = protons + neutrons.</li><li>Neutrons = mass number − atomic number.</li><li>For the first 20 elements, fill shells 2, then 8, then 8, then 2.</li><li>Losing electrons makes a positive ion; gaining electrons makes a negative ion.</li></ul></section></div>`},
      {title:"Elements, compounds and mixtures",summary:"The way particles join determines whether a substance is an element, compound or mixture.",keywords:["element","compound","mixture","molecule","chemical bond","pure substance"],body:`
        <div class="lesson-grid"><section class="note-panel"><h3>Tell them apart</h3><ul><li><strong>Element:</strong> one type of atom only.</li><li><strong>Compound:</strong> different elements chemically bonded in a fixed ratio.</li><li><strong>Mixture:</strong> two or more substances together without chemical bonds between them.</li><li>Physical methods can separate mixtures. Chemical reactions are needed to break down compounds.</li></ul></section><section class="worked-panel"><h3>Examples</h3><table class="mini-table"><tr><th>SUBSTANCE</th><th>TYPE</th><th>WHY</th></tr><tr><td>Oxygen, O₂</td><td>Element</td><td>Only oxygen atoms</td></tr><tr><td>Water, H₂O</td><td>Compound</td><td>Hydrogen and oxygen bonded</td></tr><tr><td>Air</td><td>Mixture</td><td>Several gases together</td></tr></table></section></div>`},
      {title:"The periodic table",summary:"The periodic table arranges elements by atomic number and reveals patterns in their properties.",keywords:["atomic number","group","period","metal","non-metal","metalloid"],body:`
        <div class="lesson-grid"><section class="note-panel"><h3>How it is organised</h3><ul><li>Atomic number increases across the table.</li><li>Rows are periods. Columns are groups.</li><li>Elements in the same group have similar properties because they have the same number of outer-shell electrons.</li><li>Metals sit on the left and centre. Non-metals sit mostly on the right. Metalloids follow the zig-zag boundary.</li></ul></section><section class="visual-panel"><h3>Groups to recognise</h3><div class="periodic-mini"><div class="element-tile"><strong>1</strong><small>Alkali metals</small></div><div class="element-tile"><strong>2</strong><small>Alkaline earth</small></div><div class="element-tile"><strong>17</strong><small>Halogens</small></div><div class="element-tile"><strong>18</strong><small>Noble gases</small></div></div><div class="callout"><strong>First 20:</strong> Know common names, symbols and how electrons fill 2, 8, 8.</div></section></div>`},
      {title:"Acids, bases and pH",summary:"pH measures how acidic or alkaline a solution is. Indicators show an estimated pH through colour.",keywords:["acid","base","alkali","pH","indicator","neutralisation"],body:`
        <div class="lesson-grid"><section class="note-panel"><h3>The pH scale</h3><ul><li>Acids have pH values below 7 and release H⁺ ions in water.</li><li>Neutral solutions have pH 7.</li><li>Alkaline solutions have pH values above 7. Alkalis release OH⁻ ions in water.</li><li>Neutralisation between an acid and a base produces a salt and water.</li></ul><div class="ph-scale"><span class="ph-marker"></span></div><div class="ph-labels"><span>0 STRONG ACID</span><span>7 NEUTRAL</span><span>14 STRONG ALKALI</span></div></section><section class="key-panel"><h3>Indicators</h3><p>Universal indicator gives a range of colours. Red and orange show acidic solutions, green shows neutral, and blue or purple shows alkaline solutions.</p><p>Diluting an acid moves its pH toward 7. Diluting an alkali also moves its pH toward 7.</p></section></div>`},
      {title:"Acid reactions",summary:"Acids react with some metals to make a salt and hydrogen gas.",keywords:["reactant","product","hydrogen","salt","corrosive","pop test"],body:`
        <div class="lesson-grid"><section class="note-panel"><h3>Acid + metal</h3><div class="formula">acid + metal → salt + hydrogen</div><p>Magnesium reacting with hydrochloric acid produces magnesium chloride and hydrogen gas.</p><div class="formula">2HCl + Mg → MgCl₂ + H₂</div></section><section class="worked-panel"><h3>Evidence of reaction</h3><ul><li>Bubbles show that a gas forms.</li><li>The magnesium gets smaller as it reacts.</li><li>The test tube may warm as energy transfers to the surroundings.</li><li>A lit splint at the mouth of the tube gives a squeaky pop if hydrogen is present.</li></ul><div class="callout"><strong>Safety:</strong> Wear goggles. Keep the test tube open and point it away from people.</div></section></div>`},
      {title:"Separating mixtures",summary:"A separation method works because substances have different physical properties.",keywords:["filtration","evaporation","distillation","decanting","magnetic separation"],body:`
        <div class="lesson-grid"><section class="note-panel"><h3>Choose by property</h3><table class="mini-table"><tr><th>METHOD</th><th>PROPERTY USED</th></tr><tr><td>Magnetic separation</td><td>Magnetism</td></tr><tr><td>Filtration</td><td>Insoluble solid particle size</td></tr><tr><td>Evaporation</td><td>Solvent changes to gas</td></tr><tr><td>Distillation</td><td>Different boiling points</td></tr><tr><td>Decanting</td><td>Settling or density</td></tr></table></section><section class="worked-panel"><h3>Sand, salt and iron</h3><ol class="worked-steps"><li>Use a magnet to remove the iron.</li><li>Add water so the salt dissolves.</li><li>Filter to remove the sand.</li><li>Evaporate the water to recover salt, or distil to collect both salt and water.</li></ol></section></div>`}
    ]
  },
  body:{
    label:"Learning area",title:"Body Systems",intro:"How bones, muscles and connective tissues produce movement, plus how gas exchange supplies oxygen.",pathway:["Muscle types","Major muscles","How muscles work","Muscle fatigue","Functions of bones","Bone structure","Bone types","Joints, tendons and ligaments","Gas exchange and breathing"],
    lessons:[
      {title:"Muscle types and major muscles",summary:"The body contains skeletal, smooth and cardiac muscle. Skeletal muscles move bones.",keywords:["skeletal","smooth","cardiac","voluntary","involuntary"],body:`
        <div class="lesson-grid"><section class="note-panel"><h3>Three muscle types</h3><table class="mini-table"><tr><th>TYPE</th><th>CONTROL</th><th>WHERE</th></tr><tr><td>Skeletal</td><td>Mostly voluntary</td><td>Attached to bones</td></tr><tr><td>Smooth</td><td>Involuntary</td><td>Walls of organs</td></tr><tr><td>Cardiac</td><td>Involuntary</td><td>Heart only</td></tr></table></section><section class="key-panel"><h3>Major muscles</h3><p>Know the location and movement role of the biceps, triceps, deltoids, pectorals, abdominals, gluteals, quadriceps, hamstrings and gastrocnemius.</p></section></div>`},
      {title:"How muscles create movement",summary:"Skeletal muscles pull on bones and work in antagonistic pairs across joints.",keywords:["contract","relax","antagonistic pair","flexion","extension"],body:`
        <div class="lesson-grid"><section class="note-panel"><h3>Muscles can only pull</h3><ul><li>A contracting muscle becomes shorter and thicker.</li><li>The opposing muscle relaxes and lengthens.</li><li>For elbow flexion, the biceps contracts and the triceps relaxes.</li><li>For elbow extension, the triceps contracts and the biceps relaxes.</li></ul></section><section class="visual-panel"><h3>Antagonistic pair</h3><div class="lungs-flow"><article><strong>FLEXION</strong><p>Biceps contracts<br>Triceps relaxes</p></article><b>↔</b><article><strong>EXTENSION</strong><p>Triceps contracts<br>Biceps relaxes</p></article></div><div class="callout"><strong>Explain movement:</strong> name the joint action, then state which muscle contracts and which relaxes.</div></section></div>`},
      {title:"Functions and structure of bones",summary:"The skeleton supports, protects and moves the body. Bone structure balances strength with low mass.",keywords:["support","protection","marrow","compact bone","spongy bone","periosteum"],body:`
        <div class="lesson-grid"><section class="note-panel"><h3>Functions of the skeleton</h3><ul><li>Support and body shape.</li><li>Protection of organs.</li><li>Movement through joints and muscle attachment.</li><li>Blood cell production in marrow.</li><li>Storage of minerals such as calcium.</li></ul></section><section class="worked-panel"><h3>Inside a long bone</h3><table class="mini-table"><tr><th>STRUCTURE</th><th>FUNCTION</th></tr><tr><td>Periosteum</td><td>Tough outer membrane; blood supply and repair</td></tr><tr><td>Compact bone</td><td>Dense strength</td></tr><tr><td>Spongy bone</td><td>Light honeycomb structure</td></tr><tr><td>Marrow</td><td>Soft tissue; makes blood cells or stores fat</td></tr><tr><td>Cartilage</td><td>Reduces friction at joint ends</td></tr></table></section></div>`},
      {title:"Bone types, joints and connective tissue",summary:"Bone shape suits function. Joints and connective tissues control movement and stability.",keywords:["long bone","short bone","flat bone","irregular bone","tendon","ligament","cartilage"],body:`
        <div class="lesson-grid"><section class="note-panel"><h3>Four bone types</h3><ul><li>Long bones act as levers, such as the femur and humerus.</li><li>Short bones provide stability with small movements, such as carpals.</li><li>Flat bones protect organs and provide broad muscle attachment, such as the skull.</li><li>Irregular bones have specialised shapes, such as vertebrae.</li></ul></section><section class="note-panel"><h3>Connective tissues</h3><ul><li>Tendons connect muscle to bone.</li><li>Ligaments connect bone to bone and stabilise joints.</li><li>Cartilage covers bone ends and reduces friction.</li></ul></section><section class="worked-panel wide"><h3>Joint types</h3><p><strong>Hinge joints</strong>, such as the knee and elbow, mainly move in one plane. <strong>Ball-and-socket joints</strong>, such as the shoulder and hip, move in many directions.</p></section></div>`},
      {title:"Exercise and muscle fatigue",summary:"Working muscles need energy. Fatigue develops when the demand for energy outpaces the body’s ability to sustain force.",keywords:["fatigue","oxygen","glucose","respiration","recovery"],body:`
        <div class="lesson-grid"><section class="note-panel"><h3>During exercise</h3><ul><li>Muscles need more energy for repeated contraction.</li><li>Heart rate and breathing rate increase to deliver more oxygen and glucose.</li><li>Blood also removes carbon dioxide and heat.</li><li>Fatigue can reduce force, speed and movement control.</li></ul></section><section class="key-panel"><h3>Investigation thinking</h3><p>For a repeated movement test, keep technique, timing and range of motion consistent. Record results at regular intervals and identify the pattern before explaining it.</p></section></div>`},
      {title:"Gas exchange and breathing",summary:"Ventilation moves air. Diffusion exchanges oxygen and carbon dioxide between alveoli and blood.",keywords:["ventilation","alveoli","diffusion","diaphragm","capillary","gas exchange"],body:`
        <div class="lesson-grid"><section class="note-panel"><h3>Breathing in</h3><ul><li>The diaphragm contracts and flattens.</li><li>The rib cage moves up and out.</li><li>Chest volume increases and pressure decreases.</li><li>Air moves into the lungs.</li></ul><h3 style="margin-top:24px">Breathing out</h3><ul><li>The diaphragm relaxes and domes upward.</li><li>The rib cage moves down and in.</li><li>Chest volume decreases and pressure increases.</li><li>Air moves out.</li></ul></section><section class="visual-panel"><h3>At the alveoli</h3><div class="lungs-flow"><article><strong>ALVEOLUS</strong><p>High oxygen<br>Low carbon dioxide</p></article><b>⇄</b><article><strong>BLOOD</strong><p>Low oxygen<br>High carbon dioxide</p></article></div><p>Oxygen diffuses into blood. Carbon dioxide diffuses into the alveolus.</p><div class="callout"><strong>Efficient surface:</strong> many alveoli give a large area. Walls are thin and moist, with a close capillary supply.</div></section></div>`}
    ]
  }
};

// Add released Google Forms URLs here. These are teacher-verified checkpoints;
// lesson ticks and quiz scores below remain local to the student's device.
const checkpointLinks={forces:"",chemistry:"",body:""};
const storage={
  get(key,fallback){try{return JSON.parse(localStorage.getItem(key))??fallback}catch{return fallback}},
  set(key,value){try{localStorage.setItem(key,JSON.stringify(value))}catch{}}
};

const practicals=[
  {unit:"forces",title:"Tug of war",aim:"Observe balanced and unbalanced forces.",equipment:"Rope, centre marker, floor line.",method:["Set the rope marker over the centre line.","Pull with equal effort and observe the marker.","Change the number or effort on one side.","Draw free body diagrams for both trials."],science:"When forces balance, net force is 0 N. When one side produces the larger force, the rope accelerates that way.",safety:"Use a clear area, closed shoes and controlled pulling. Stop immediately if anyone falls."},
  {unit:"forces",title:"Sprint acceleration",aim:"Calculate speed over sections of a sprint and identify acceleration.",equipment:"Measured course, cones, stopwatches.",method:["Mark equal sections of the course.","Record cumulative time at each marker.","Calculate speed for each section.","Compare the speeds and identify where acceleration occurred."],science:"Acceleration occurs when velocity changes. Repeated trials improve reliability.",safety:"Check the surface, warm up and leave enough stopping distance."},
  {unit:"forces",title:"Ramp investigation",aim:"Investigate how ramp angle affects the motion of a trolley or ball.",equipment:"Ramp, trolley or ball, blocks, tape measure, stopwatch.",method:["Choose several ramp heights or angles.","Keep release point and travel distance the same.","Release without pushing and record time.","Repeat each setting and calculate mean speed."],science:"A steeper ramp increases the component of gravity acting down the ramp, so acceleration usually increases.",safety:"Use a stop block and keep hands and feet clear of the moving object."},
  {unit:"chemistry",title:"Phase change of water",aim:"Observe water changing state and record temperature over time.",equipment:"Ice, beaker, thermometer, retort stand, tripod, gauze, heat mat, Bunsen burner, stopwatch.",method:["Place enough ice in the beaker to cover the thermometer bulb.","Hold the thermometer so it does not touch the glass.","Record temperature and state every minute while heating.","Continue until the water reaches boiling."],science:"Temperature can stay nearly constant during melting or boiling because added energy changes particle arrangement rather than raising average kinetic energy.",safety:"Wear goggles. Tie back hair. Handle hot glassware with care and never leave the flame unattended."},
  {unit:"chemistry",title:"Household pH",aim:"Estimate the pH of common solutions using universal indicator.",equipment:"Spotting tile, dropper, universal indicator, toothpicks, labelled solutions, pH chart.",method:["Place a small amount of each labelled solution in separate wells.","Add 2–3 drops of universal indicator.","Stir with a clean toothpick and record the colour.","Match the colour to the chart and classify the solution."],science:"Indicator colour gives an estimated pH. Red or orange indicates acid, green neutral, and blue or purple alkaline.",safety:"Wear goggles. Use a clean dropper for each solution. Do not taste substances."},
  {unit:"chemistry",title:"Hydrogen pop test",aim:"React magnesium with dilute hydrochloric acid and test for hydrogen gas.",equipment:"Test tube, rack, magnesium ribbon, dilute hydrochloric acid, lit wooden splint, tongs.",method:["Add about 5 mL of dilute hydrochloric acid to a test tube.","Add a small strip of magnesium ribbon.","When bubbling begins, bring a lit splint to the mouth of the tube.","Record the sound and other observations."],science:"Acid plus metal produces a salt and hydrogen. A squeaky pop confirms hydrogen gas.",safety:"Wear goggles. Keep the test tube open, point it away from people and keep the flame away from the liquid."},
  {unit:"chemistry",title:"Separating a mixture",aim:"Separate sand, salt and iron using physical properties.",equipment:"Magnet in a bag, beakers, water, stirring rod, filter funnel and paper, evaporating dish, heating equipment.",method:["Use the magnet to remove iron.","Add warm water to dissolve salt.","Decant, then filter to remove sand.","Gently evaporate the water to recover salt."],science:"Each step uses a different physical property: magnetism, solubility, particle size and boiling point.",safety:"Wear goggles. Heat gently. Keep the magnet dry and handle hot equipment with tongs."},
  {unit:"body",title:"Muscle fatigue investigation",aim:"Measure how repeated exercise affects muscle performance.",equipment:"Timer and a chosen repeatable movement.",method:["Choose a fixed movement and clear success rule.","Record repetitions in equal time intervals.","Continue for the agreed duration.","Graph results and describe the pattern."],science:"Repeated contraction uses energy and performance may decrease as fatigue develops. Consistent technique makes comparisons fair.",safety:"Use a low-risk movement, warm up and stop for pain, dizziness or poor technique."},
  {unit:"body",title:"Bone strength model",aim:"Test how structure affects the strength of a model bone.",equipment:"Paper, tape, equal masses and supports.",method:["Create paper models with different structures.","Keep paper size and span the same.","Add mass gradually until each model deforms.","Repeat and compare maximum load."],science:"Shape and distribution of material affect strength. Hollow structures can resist bending while remaining light.",safety:"Keep falling masses low and feet clear."},
  {unit:"body",title:"Chicken wing dissection",aim:"Identify muscles, tendons, ligaments, cartilage and joints in a real limb.",equipment:"Chicken wing, tray, gloves, goggles, scissors or scalpel, forceps.",method:["Inspect the outside and locate joint movement.","Open the skin carefully to expose muscles.","Pull selected muscles and observe movement.","Identify tendon, ligament and cartilage before disposal."],science:"Contracting muscles pull through tendons to move bones at joints. Ligaments stabilise the joint and cartilage reduces friction.",safety:"Wear gloves and goggles. Cut away from hands. Disinfect surfaces and wash hands thoroughly."}
];

const practicalGuides={
  "Tug of war":{iv:"Pulling force or team arrangement",dv:"Direction and change in motion of the marker",controls:"Same rope, surface, start line and pull time",results:"Record forces or team arrangement, marker movement and direction.",graph:"Use a bar graph only if force or distance measurements are numerical.",conclusion:"Link zero net force to no acceleration and a non-zero net force to acceleration.",improvement:"Measure force with force meters and repeat each arrangement.",finish:"Draw two labelled free-body diagrams and explain both outcomes."},
  "Sprint acceleration":{iv:"Distance section or time interval",dv:"Calculated speed in each section",controls:"Same runner, course, start method and timing method",results:"Record distance and time, then calculate speed for each section and a mean from repeats.",graph:"Plot distance or time interval against speed.",conclusion:"Identify where speed changed and therefore where acceleration occurred.",improvement:"Use video timing or light gates to reduce reaction-time error.",finish:"Show calculations, a graph and an evidence-based description of acceleration."},
  "Ramp investigation":{iv:"Ramp height or angle",dv:"Travel time, speed or acceleration",controls:"Same object, distance, surface and release method",results:"Record repeated times and calculate mean speed for each setting.",graph:"Plot ramp height or angle against mean speed.",conclusion:"Describe the pattern and connect it to the force acting down the ramp.",improvement:"Use a release gate and electronic timing.",finish:"Test at least four settings, graph the means and explain the trend."},
  "Phase change of water":{iv:"Heating time",dv:"Water temperature and physical state",controls:"Same water mass, heating rate, beaker and thermometer position",results:"Record time, temperature, state and observations at regular intervals.",graph:"Plot time against temperature and mark phase changes.",conclusion:"Explain flat regions using energy and particle arrangement.",improvement:"Use a data logger and stir gently for even temperature.",finish:"Submit a labelled heating curve and particle explanation."},
  "Household pH":{iv:"Household solution tested",dv:"Indicator colour and estimated pH",controls:"Same sample volume, indicator drops, lighting and clean equipment",results:"Table the solution, colour, pH and acid/neutral/alkali classification.",graph:"A sorted pH scale or bar graph can compare the estimated values.",conclusion:"Rank the substances and support each classification with pH evidence.",improvement:"Repeat with pH paper or a calibrated pH probe.",finish:"Test all approved samples and justify every classification."},
  "Hydrogen pop test":{iv:"Metal–acid reaction mixture",dv:"Gas-test result and reaction observations",controls:"Same acid concentration and volume, metal size and apparatus",results:"Record bubbling, temperature change, metal change and pop-test result.",graph:"No graph is required; a clear observation table is appropriate.",conclusion:"Use the squeaky pop as evidence that hydrogen formed.",improvement:"Collect a consistent gas volume before testing.",finish:"Write the word equation, observations and gas identification."},
  "Separating a mixture":{iv:"Separation step used",dv:"Material recovered at each step",controls:"Same starting mixture and careful quantitative transfer",results:"Record the appearance and mass of each recovered component if balances are available.",graph:"Compare percentage recovery with a bar graph if masses are measured.",conclusion:"Explain how magnetism, solubility, particle size and boiling point enabled separation.",improvement:"Rinse residues and reduce transfer losses.",finish:"Recover three components and justify the order of methods."},
  "Muscle fatigue investigation":{iv:"Exercise time or repetition set",dv:"Successful repetitions, force or hold time",controls:"Same participant, movement, technique, interval and recovery",results:"Record performance for equal intervals and repeat where safe.",graph:"Plot time or set number against performance.",conclusion:"Describe the trend and explain it using energy demand and fatigue.",improvement:"Standardise movement range and include planned recovery.",finish:"Present a safe fair test, graph and evidence-based fatigue explanation."},
  "Bone strength model":{iv:"Model-bone shape or structure",dv:"Maximum supported load before deformation",controls:"Same paper, span, length, load position and loading rate",results:"Record maximum load for repeated models and calculate a mean.",graph:"Use a bar graph of model structure against mean maximum load.",conclusion:"Relate strength differences to shape and distribution of material.",improvement:"Build more identical replicas and add smaller mass steps.",finish:"Test at least three structures and justify the strongest design."},
  "Chicken wing dissection":{iv:"Not a fair-test variable; this is an anatomical observation",dv:"Identified structures and observed movement",controls:"Follow the same dissection sequence and identification criteria",results:"Use a labelled diagram or table for muscle, tendon, ligament, cartilage and joint.",graph:"No graph is required for this qualitative investigation.",conclusion:"Explain how contracting muscles pull tendons to move bones and how joints are stabilised.",improvement:"Use clearer labels, multiple views and careful separation of tissues.",finish:"Produce a labelled record connecting each structure to its function."}
};

const revision={
  forces:{cards:[["What is net force?","The overall force after forces in the same direction are added and opposing forces are subtracted."],["What do balanced forces do?","They give a net force of 0 N, so there is no acceleration."],["State the speed equation.","speed = distance ÷ time"],["What does the gradient of a distance-time graph show?","Speed."],["State Newton’s second law.","Net force equals mass multiplied by acceleration: F = ma."],["How is work calculated?","work = force × distance"]],quiz:[
    {q:"A box has 80 N right and 35 N left. What is the net force?",o:["45 N right","45 N left","115 N right","0 N"],a:0,e:"Subtract opposing forces: 80 − 35 = 45 N toward the larger force."},
    {q:"A runner covers 150 m in 30 s. What is the average speed?",o:["4 m/s","5 m/s","30 m/s","180 m/s"],a:1,e:"150 ÷ 30 = 5 m/s."},
    {q:"Which distance-time graph feature means stationary?",o:["Steep rising line","Curved line","Horizontal line","Falling line"],a:2,e:"Distance does not change during a horizontal section."},
    {q:"A 3 kg object accelerates at 4 m/s². What net force acts?",o:["0.75 N","7 N","12 N","24 N"],a:2,e:"F = ma = 3 × 4 = 12 N."},
    {q:"Which statement describes a Newton’s third law pair?",o:["Two forces on one box balance","A foot pushes the ground and the ground pushes the foot","A car slows because of drag","A heavy object has more inertia"],a:1,e:"The equal opposite forces act on two different objects."}]},
  chemistry:{cards:[["What is matter?","Anything that has mass and takes up space."],["Where are protons and neutrons?","In the nucleus."],["How is a compound different from a mixture?","A compound has different elements chemically bonded; mixture substances are not chemically bonded."],["What does atomic number tell us?","The number of protons in the nucleus."],["What pH is neutral?","pH 7."],["Complete: acid + metal…","salt + hydrogen"],["Which method separates an insoluble solid from a liquid?","Filtration."],["Why do group elements have similar properties?","They have the same number of outer-shell electrons."]],quiz:[
    {q:"Which particle has a negative charge?",o:["Proton","Neutron","Electron","Nucleus"],a:2,e:"Electrons have charge −1."},
    {q:"Which is a compound?",o:["Air","Gold","Water","Oxygen"],a:2,e:"Water contains hydrogen and oxygen chemically bonded."},
    {q:"An indicator turns purple. The solution is most likely…",o:["Strongly acidic","Weakly acidic","Neutral","Alkaline"],a:3,e:"Blue and purple universal indicator colours show alkaline solutions."},
    {q:"What gas gives a squeaky pop with a lit splint?",o:["Oxygen","Hydrogen","Carbon dioxide","Nitrogen"],a:1,e:"The pop test identifies hydrogen."},
    {q:"Which method could recover water from salt solution?",o:["Filtration","Magnetism","Distillation","Decanting"],a:2,e:"Distillation evaporates and then condenses the water."},
    {q:"An element has atomic number 12. How many protons does it have?",o:["6","10","12","24"],a:2,e:"Atomic number equals proton number."}]},
  body:{cards:[["Name the three types of muscle.","Skeletal, smooth and cardiac."],["What connects muscle to bone?","A tendon."],["What connects bone to bone?","A ligament."],["During elbow flexion, what do the biceps and triceps do?","The biceps contracts and the triceps relaxes."],["What does compact bone provide?","Dense strength."],["What happens to the diaphragm during inhalation?","It contracts and flattens."],["Where does gas exchange occur?","Across the walls of the alveoli and surrounding capillaries."],["Give two alveolus adaptations.","Large surface area, thin walls, moist surface and close blood supply; any two."]],quiz:[
    {q:"Which muscle type is found only in the heart?",o:["Skeletal","Smooth","Cardiac","Voluntary"],a:2,e:"Cardiac muscle forms the muscular wall of the heart."},
    {q:"Which tissue reduces friction at the ends of bones?",o:["Tendon","Cartilage","Marrow","Periosteum"],a:1,e:"Cartilage provides a smooth joint surface."},
    {q:"During elbow extension, which muscle contracts?",o:["Biceps","Triceps","Deltoid","Quadriceps"],a:1,e:"The triceps contracts to extend the elbow."},
    {q:"Why do alveoli have thin walls?",o:["To store more air","To shorten diffusion distance","To make mucus","To increase pressure"],a:1,e:"A short diffusion distance speeds gas exchange."},
    {q:"When breathing in, chest volume…",o:["decreases","stays fixed","increases","becomes zero"],a:2,e:"The diaphragm contracts and the rib cage moves up and out, increasing volume."},
    {q:"Oxygen moves from alveoli into blood by…",o:["diffusion","filtration","contraction","evaporation"],a:0,e:"Particles diffuse from higher to lower concentration."}]}
};

const examQuestions=[revision.forces.quiz[0],revision.chemistry.quiz[0],revision.body.quiz[0],revision.forces.quiz[1],revision.chemistry.quiz[1],revision.body.quiz[1],revision.forces.quiz[2],revision.chemistry.quiz[2],revision.body.quiz[2],revision.forces.quiz[3],revision.chemistry.quiz[3],revision.body.quiz[3],revision.forces.quiz[4],revision.chemistry.quiz[4],revision.body.quiz[4]];

let currentTerm="forces",currentLesson=0,revisionMode="cards",cardIndex=0;

function completedLessons(){return storage.get("y10-completed",{})}
function lessonIsComplete(term,index){return Boolean(completedLessons()[`${term}-${index}`])}
function setLessonComplete(term,index,value){const done=completedLessons();done[`${term}-${index}`]=value;storage.set("y10-completed",done)}
function bestQuiz(term){return storage.get(`y10-best-${term}`,null)}
function saveBestQuiz(term,score,total){const result={score,total,percent:Math.round(score/total*100),date:new Date().toISOString()};const old=bestQuiz(term);if(!old||result.percent>old.percent)storage.set(`y10-best-${term}`,result)}

function showPage(name){
  const page=document.querySelector(`[data-page="${name}"]`)||document.querySelector('[data-page="home"]');
  document.querySelectorAll('.page').forEach(p=>p.classList.toggle('active',p===page));
  document.querySelectorAll('[data-route]').forEach(a=>a.classList.toggle('active',a.dataset.route===page.dataset.page));
  document.querySelector('#site-nav').classList.remove('open');document.querySelector('.menu-button').setAttribute('aria-expanded','false');
  window.scrollTo(0,0);
  if(name==="learn") renderUnit();
  if(name==="progress") renderProgress();
}
document.querySelectorAll('[data-route]').forEach(link=>link.addEventListener('click',e=>{e.preventDefault();location.hash=link.dataset.route;showPage(link.dataset.route)}));
document.querySelectorAll('[data-open-term]').forEach(btn=>btn.addEventListener('click',()=>{currentTerm=btn.dataset.openTerm;currentLesson=0;location.hash="learn";showPage("learn")}));
window.addEventListener('hashchange',()=>showPage(location.hash.slice(1)||"home"));
document.querySelector('.menu-button').addEventListener('click',e=>{const nav=document.querySelector('#site-nav');nav.classList.toggle('open');e.currentTarget.setAttribute('aria-expanded',String(nav.classList.contains('open')))});

function renderUnit(){
  const unit=units[currentTerm];
  document.querySelectorAll('[data-term]').forEach(b=>b.classList.toggle('active',b.dataset.term===currentTerm));
  const completed=unit.lessons.filter((_,i)=>lessonIsComplete(currentTerm,i)).length;
  document.querySelector('#unit-overview').innerHTML=`<div class="unit-head"><div><p class="eyebrow dark">${unit.label.toUpperCase()}</p><h2>${unit.title}</h2><p>${unit.intro}</p></div><span class="unit-chip">${completed}/${unit.lessons.length} COMPLETE</span></div><div class="topic-pathway"><strong>Taught sequence</strong>${unit.pathway.map(x=>`<span>${x}</span>`).join('')}</div>`;
  const tabs=document.querySelector('#lesson-tabs');tabs.innerHTML=unit.lessons.map((l,i)=>`<button role="tab" aria-selected="${i===currentLesson}" class="${i===currentLesson?'active':''}" data-lesson="${i}">${i+1}. ${l.title}</button>`).join('');
  tabs.querySelectorAll('button').forEach(b=>b.onclick=()=>{currentLesson=Number(b.dataset.lesson);renderUnit()});
  const l=unit.lessons[currentLesson];
  const checked=lessonIsComplete(currentTerm,currentLesson);
  const form=checkpointLinks[currentTerm];
  const interactive=window.Y10Interactives?.html(currentTerm,currentLesson)||"";
  document.querySelector('#lesson-content').innerHTML=`<header class="lesson-title"><span>${String(currentLesson+1).padStart(2,'0')}</span><div><h2>${l.title}</h2><p>${l.summary}</p></div></header>${l.body}${interactive}<div class="keyword-row">${l.keywords.map(k=>`<span>${k}</span>`).join('')}</div><div class="lesson-actions"><label><input id="lesson-complete" type="checkbox" ${checked?'checked':''}> I have completed this learning section</label>${currentLesson<unit.lessons.length-1?`<button class="next-question" id="next-lesson">Next section</button>`:`<a class="primary-button" href="#revise" data-route="revise">Start ${unit.title} revision</a>`}</div><section class="verified-checkpoint"><div><p class="eyebrow dark">TEACHER-VERIFIED PROGRESS</p><h3>Learning-area checkpoint</h3><p>Your ticks and practice scores stay on this device. A released Google Form collects your school email for verified evidence.</p></div>${form?`<a class="primary-button" href="${form}" target="_blank" rel="noopener">Open verified checkpoint</a>`:`<span>Checkpoint link will appear when your kaiako releases it.</span>`}</section>`;
  document.querySelector('#lesson-complete').onchange=e=>{setLessonComplete(currentTerm,currentLesson,e.currentTarget.checked);renderUnit()};
  const next=document.querySelector('#next-lesson');if(next)next.onclick=()=>{currentLesson++;renderUnit();window.scrollTo(0,260)};
  initLessonTools();
  window.Y10Interactives?.init(currentTerm,currentLesson);
}
document.querySelectorAll('[data-term]').forEach(b=>b.addEventListener('click',()=>{currentTerm=b.dataset.term;currentLesson=0;renderUnit()}));

function progressLevel(term){const quiz=bestQuiz(term),done=units[term].lessons.some((_,i)=>lessonIsComplete(term,i));if(!quiz&&!done)return ["Not started","not-started"];if(quiz?.percent>=90)return ["Mastered","mastered"];if(quiz?.percent>=70)return ["Secure","secure"];return ["Developing","developing"]}
function renderProgress(){
  const grid=document.querySelector('#progress-grid');
  document.querySelector('#student-name').value=storage.get("y10-student-name","");
  document.querySelector('#student-class').value=storage.get("y10-student-class","");
  grid.innerHTML=Object.entries(units).map(([term,unit])=>{const done=unit.lessons.filter((_,i)=>lessonIsComplete(term,i)).length,pct=Math.round(done/unit.lessons.length*100),quiz=bestQuiz(term),[level,cls]=progressLevel(term),form=checkpointLinks[term];return `<article class="progress-card"><div><span class="status ${cls}">${level}</span><h2>${unit.title}</h2></div><p><strong>${done}/${unit.lessons.length}</strong> learning sections completed</p><progress max="100" value="${pct}">${pct}%</progress><p>${quiz?`Best practice score: <strong>${quiz.score}/${quiz.total} (${quiz.percent}%)</strong>`:"Practice checkpoint not attempted"}</p><div class="progress-actions"><a class="primary-button" href="#learn" data-progress-term="${term}">Continue learning</a>${form?`<a class="secondary-button" href="${form}" target="_blank" rel="noopener">Verified Form</a>`:""}</div></article>`}).join('');
  grid.querySelectorAll('[data-progress-term]').forEach(a=>a.onclick=()=>{currentTerm=a.dataset.progressTerm;currentLesson=0});
}
document.querySelector('#student-name').oninput=e=>storage.set("y10-student-name",e.target.value);
document.querySelector('#student-class').oninput=e=>storage.set("y10-student-class",e.target.value);
document.querySelector('#copy-progress').onclick=async()=>{const lines=[`MANUKURA Year 10 Pūtaiao progress — ${new Date().toLocaleDateString('en-NZ')}`,`Student: ${storage.get("y10-student-name","")||"Not entered"}`,`Class: ${storage.get("y10-student-class","")||"Not entered"}`,"Device record only — teacher verification is through released Google Forms.",...Object.entries(units).map(([term,unit])=>{const done=unit.lessons.filter((_,i)=>lessonIsComplete(term,i)).length,quiz=bestQuiz(term),[level]=progressLevel(term);return `${unit.title}: ${level}; ${done}/${unit.lessons.length} sections; best practice ${quiz?`${quiz.score}/${quiz.total} (${quiz.percent}%)`:"not attempted"}`})];try{await navigator.clipboard.writeText(lines.join('\n'));document.querySelector('#copy-feedback').textContent="Progress summary copied."}catch{document.querySelector('#copy-feedback').textContent="Copy was blocked. Select and copy from your browser."}};

function initLessonTools(){
  const distance=document.querySelector('#distance-input'),time=document.querySelector('#time-input');
  if(!distance||!time)return;
  const calculate=()=>{const d=Number(distance.value),t=Number(time.value),speed=t>0?d/t:0;document.querySelector('#speed-input').value=Number.isFinite(speed)?speed.toFixed(2):"";document.querySelector('#motion-result').textContent=t>0?`${d} ÷ ${t} = ${speed.toFixed(2)} m/s`:"Time must be greater than 0."};
  distance.oninput=calculate;time.oninput=calculate;calculate();
}

function renderPracticals(filter="all"){
  const list=filter==="all"?practicals:practicals.filter(p=>p.unit===filter);
  document.querySelector('#practical-grid').innerHTML=list.map((p,i)=>`<button class="practical-card" data-practical="${practicals.indexOf(p)}"><span class="tag">${units[p.unit].title}</span><h3>${p.title}</h3><p>${p.aim}</p><b>Open investigation</b></button>`).join('');
  document.querySelectorAll('[data-practical]').forEach(b=>b.onclick=()=>openPractical(Number(b.dataset.practical)));
}
document.querySelectorAll('[data-practical-filter]').forEach(b=>b.onclick=()=>{document.querySelectorAll('[data-practical-filter]').forEach(x=>x.classList.toggle('active',x===b));renderPracticals(b.dataset.practicalFilter)});
function openPractical(i){const p=practicals[i],g=practicalGuides[p.title],dialog=document.querySelector('#practical-dialog');document.querySelector('#dialog-content').innerHTML=`<div class="dialog-inner"><p class="eyebrow dark">${units[p.unit].title.toUpperCase()}</p><h2>${p.title}</h2><div class="dialog-section"><h3>QUESTION / AIM</h3><p>${p.aim}</p></div><div class="dialog-section"><h3>EQUIPMENT</h3><p>${p.equipment}</p></div><div class="safety"><strong>Safety:</strong> ${p.safety}</div><div class="dialog-section"><h3>VARIABLES AND CONTROLS</h3><p><strong>Independent variable:</strong> ${g.iv}</p><p><strong>Dependent variable:</strong> ${g.dv}</p><p><strong>Controls:</strong> ${g.controls}</p></div><div class="dialog-section"><h3>METHOD</h3><ol>${p.method.map(s=>`<li>${s}</li>`).join('')}</ol></div><div class="dialog-section"><h3>RESULTS AND GRAPH</h3><p>${g.results}</p><p>${g.graph}</p></div><div class="dialog-section"><h3>CONCLUSION AND IMPROVEMENT</h3><p>${g.conclusion}</p><p><strong>Improve:</strong> ${g.improvement}</p></div><div class="dialog-section finish-line"><h3>CLEAR FINISH LINE</h3><p>${g.finish}</p></div><div class="dialog-section"><h3>THE SCIENCE</h3><p>${p.science}</p></div></div>`;dialog.showModal()}
document.querySelector('.dialog-close').onclick=()=>document.querySelector('#practical-dialog').close();
document.querySelector('#practical-dialog').addEventListener('click',e=>{if(e.target===e.currentTarget)e.currentTarget.close()});

function renderRevision(){cardIndex=0;revisionMode=document.querySelector('[data-mode].active').dataset.mode;const term=document.querySelector('#revision-term').value;if(revisionMode==="cards")renderCard();else renderQuiz(document.querySelector('#revision-stage'),revision[term].quiz,undefined,term)}
function renderCard(){const term=document.querySelector('#revision-term').value,cards=revision[term].cards,[q,a]=cards[cardIndex];document.querySelector('#revision-stage').innerHTML=`<div class="flashcard-shell"><button class="card-nav" id="prev-card" aria-label="Previous card">‹</button><button class="revision-card" id="revision-card"><span class="card-count">CARD ${cardIndex+1} OF ${cards.length}</span><h2 class="question">${q}</h2><h2 class="answer">${a}</h2></button><button class="card-nav" id="next-card" aria-label="Next card">›</button></div><p class="card-instruction">Answer aloud, then tap the card to reveal.</p>`;document.querySelector('#revision-card').onclick=e=>e.currentTarget.classList.toggle('flipped');document.querySelector('#prev-card').onclick=()=>{cardIndex=(cardIndex-1+cards.length)%cards.length;renderCard()};document.querySelector('#next-card').onclick=()=>{cardIndex=(cardIndex+1)%cards.length;renderCard()}}
document.querySelector('#revision-term').onchange=renderRevision;
document.querySelectorAll('[data-mode]').forEach(b=>b.onclick=()=>{document.querySelectorAll('[data-mode]').forEach(x=>x.classList.toggle('active',x===b));renderRevision()});

function renderQuiz(container,questions,onComplete,saveTerm){let index=0,score=0,answers=[];function render(){if(index>=questions.length){if(saveTerm)saveBestQuiz(saveTerm,score,questions.length);if(onComplete)return onComplete(score,answers);container.innerHTML=`<div class="quiz-card"><p class="eyebrow dark">COMPLETE</p><h3>Quick check finished</h3><div class="quiz-score">${score}/${questions.length}</div><p>${score===questions.length?'Ka mau te wehi. Full marks.':score>=Math.ceil(questions.length*.65)?'Good work. Review the explanations, then try again.':'Return to the learning sections, then have another attempt.'}</p><p>Your best practice score is saved on this device.</p><button class="next-question">Try again</button></div>`;container.querySelector('button').onclick=()=>{index=0;score=0;answers=[];render()};return}const item=questions[index];container.innerHTML=`<div class="quiz-card"><div class="quiz-progress">QUESTION ${index+1} OF ${questions.length}</div><div class="quiz-question">${item.q}</div><div class="options">${item.o.map((o,i)=>`<button class="option" data-answer="${i}">${o}</button>`).join('')}</div><div class="quiz-feedback" aria-live="polite"></div><button class="next-question" hidden>${index===questions.length-1?'Finish':'Next question'}</button></div>`;const opts=[...container.querySelectorAll('.option')],feedback=container.querySelector('.quiz-feedback'),next=container.querySelector('.next-question');opts.forEach(btn=>btn.onclick=()=>{if(opts.some(o=>o.disabled))return;const chosen=Number(btn.dataset.answer),correct=chosen===item.a;opts.forEach(o=>o.disabled=true);btn.classList.add(correct?'correct':'wrong');opts[item.a].classList.add('correct');if(correct)score++;answers.push({item,chosen,correct});feedback.textContent=(correct?'Correct. ':'Not quite. ')+item.e;next.hidden=false});next.onclick=()=>{index++;render()}}render()}

const checklistItems=[["Forces and free body diagrams","Draw and label forces with size and direction."],["Motion calculations","Rearrange and use speed, acceleration, work and F = ma."],["Motion graphs","Interpret gradient, stationary sections and changing motion."],["Atoms and periodic patterns","Use atomic number, particle charge, groups and periods."],["Acids, bases and reactions","Read pH, explain indicators and describe the hydrogen test."],["Mixtures and separation","Choose a method using a physical property."],["Muscles, bones and joints","Connect structure to movement and function."],["Gas exchange","Explain breathing, diffusion and alveolus adaptations."],["Science investigation skills","Identify variables, describe patterns and evaluate a method."]];
document.querySelector('#exam-checklist').innerHTML=checklistItems.map((x,i)=>`<div class="check-item"><input id="check-${i}" type="checkbox"><label for="check-${i}">${x[0]}<small>${x[1]}</small></label></div>`).join('');
document.querySelector('#start-exam').onclick=()=>{document.querySelector('#start-exam').hidden=true;renderQuiz(document.querySelector('#exam-stage'),examQuestions,(score,answers)=>{const stage=document.querySelector('#exam-stage');stage.innerHTML=`<div class="test-summary"><p class="eyebrow dark">RESULT</p><h3>Mixed practice complete</h3><div class="quiz-score">${score}/${examQuestions.length}</div><p>${score>=12?'Strong result. Check every explanation and practise any item you guessed.':score>=9?'You have the main ideas. Use the review below to target the gaps.':'Return to the matching learning sections before retrying.'}</p><div class="answer-review">${answers.map((r,i)=>`<div class="review-item ${r.correct?'correct':'wrong'}"><strong>${r.correct?'Correct':'Review'}: Question ${i+1}</strong><p>${r.item.e}</p></div>`).join('')}</div><button class="next-question" id="retry-exam">Try again</button></div>`;document.querySelector('#retry-exam').onclick=()=>document.querySelector('#start-exam').click()})};

renderPracticals();renderRevision();showPage(location.hash.slice(1)||"home");
