units.body={
    label:"Learning area",title:"Body Systems",intro:"Muscles, bones, joints and gas exchange, organised as the sequence needed for your body-systems assessment.",
    lessons:[
      lesson("Muscle types","The body contains skeletal, smooth and cardiac muscle.",[
        "Skeletal muscle is attached to bones and is mostly voluntary.","Smooth muscle is involuntary and found in the walls of organs.","Cardiac muscle is involuntary and found only in the heart."
      ],`<div class="lesson-grid"><section class="note-panel"><h3>Three types</h3><table class="mini-table"><tr><th>TYPE</th><th>CONTROL</th><th>WHERE</th></tr><tr><td>Skeletal</td><td>Mostly voluntary</td><td>Attached to bones</td></tr><tr><td>Smooth</td><td>Involuntary</td><td>Walls of organs</td></tr><tr><td>Cardiac</td><td>Involuntary</td><td>Heart</td></tr></table></section><section class="key-panel"><h3>Function</h3><p>Skeletal muscle produces body movement by pulling on bones through tendons.</p></section></div>`,[
        mcq("Which muscle type is found only in the heart?",["skeletal","smooth","cardiac","voluntary"],2,"Cardiac muscle forms the muscular wall of the heart."),
        mcq("Which muscle type moves bones at joints?",["skeletal","smooth","cardiac","all equally"],0,"Skeletal muscles attach to bones through tendons.")
      ],0,["skeletal","smooth","cardiac"]),
      lesson("Major muscles","Identify major muscles and connect them to common movements.",[
        "Know the locations of biceps, triceps, deltoids, pectorals, abdominals, gluteals, quadriceps, hamstrings and gastrocnemius.","Connect a muscle to a movement it helps produce."
      ],`<div class="lesson-grid"><section class="note-panel"><h3>Front of body</h3><table class="mini-table"><tr><th>MUSCLE</th><th>LOCATION</th><th>COMMON ROLE</th></tr><tr><td>Deltoids</td><td>shoulder</td><td>raise/move arm</td></tr><tr><td>Pectorals</td><td>chest</td><td>move arm across body</td></tr><tr><td>Biceps</td><td>front upper arm</td><td>elbow flexion</td></tr><tr><td>Abdominals</td><td>front trunk</td><td>trunk flexion/stability</td></tr><tr><td>Quadriceps</td><td>front thigh</td><td>knee extension</td></tr></table></section><section class="note-panel"><h3>Back of body</h3><table class="mini-table"><tr><th>MUSCLE</th><th>LOCATION</th><th>COMMON ROLE</th></tr><tr><td>Triceps</td><td>back upper arm</td><td>elbow extension</td></tr><tr><td>Gluteals</td><td>buttocks/hip</td><td>hip extension</td></tr><tr><td>Hamstrings</td><td>back thigh</td><td>knee flexion</td></tr><tr><td>Gastrocnemius</td><td>calf</td><td>plantar flexion</td></tr></table></section></div>`,[
        mcq("Which muscle is on the front of the upper arm?",["triceps","biceps","hamstrings","gastrocnemius"],1,"The biceps is on the anterior upper arm."),
        mcq("Which major muscle group extends the knee?",["quadriceps","hamstrings","pectorals","abdominals"],0,"The quadriceps are the main knee extensors.")
      ],null,["major muscles","biceps","triceps","quadriceps","hamstrings"]),
      lesson("How muscles create movement","Skeletal muscles pull and work in antagonistic pairs.",[
        "Muscles can pull but cannot push.","When one muscle contracts, its antagonist relaxes.","Elbow flexion: biceps contracts, triceps relaxes.","Elbow extension: triceps contracts, biceps relaxes."
      ],`<div class="lesson-grid"><section class="note-panel"><h3>Contract and relax</h3><p>A contracting skeletal muscle becomes shorter and thicker and pulls through its tendon.</p></section><section class="visual-panel"><h3>Antagonistic pair</h3><div class="lungs-flow"><article><strong>FLEXION</strong><p>Biceps contracts<br>Triceps relaxes</p></article><b>↔</b><article><strong>EXTENSION</strong><p>Triceps contracts<br>Biceps relaxes</p></article></div></section></div>`,[
        mcq("During elbow extension, which muscle contracts?",["biceps","triceps","deltoid","quadriceps"],1,"The triceps contracts to extend the elbow."),
        mcq("A muscle that opposes another muscle is its…",["ligament","antagonist","marrow","cartilage"],1,"Antagonistic pairs create opposite joint actions.")
      ],1,["contract","relax","antagonistic pair","flexion","extension"]),
      lesson("Functions of the skeleton","The skeleton supports, protects and enables movement.",[
        "The skeleton provides support and body shape.","Bones protect organs and provide levers for movement.","Bone marrow produces blood cells and bone stores minerals such as calcium."
      ],`<div class="lesson-grid"><section class="note-panel"><h3>Main functions</h3><ul><li>Support and shape.</li><li>Protection of organs.</li><li>Movement with muscles and joints.</li><li>Blood-cell production in marrow.</li><li>Mineral storage.</li></ul></section><section class="worked-panel"><h3>Examples</h3><p>Skull → protects the brain.<br>Rib cage → protects heart and lungs.<br>Femur → acts as a strong lever during movement.</p></section></div>`,[
        mcq("Which skeleton function is shown by the skull?",["gas exchange","protection","digestion","filtration"],1,"The skull protects the brain."),
        mcq("Where are blood cells produced?",["cartilage","bone marrow","tendon","ligament"],1,"Red marrow produces blood cells.")
      ],null,["skeleton","support","protection","movement","marrow"]),
      lesson("Structure of a long bone","Different tissues make bones strong, light, supplied and able to repair.",[
        "Periosteum is a tough outer membrane involved in blood supply and repair.","Compact bone provides dense strength; spongy bone reduces mass while remaining strong.","Marrow is soft tissue inside bone; cartilage reduces friction at joint surfaces.","Blood vessels carry oxygen and nutrients."
      ],`<div class="lesson-grid"><section class="note-panel"><h3>Long-bone structures</h3><table class="mini-table"><tr><th>STRUCTURE</th><th>FUNCTION</th></tr><tr><td>Periosteum</td><td>outer membrane; blood supply and repair</td></tr><tr><td>Compact bone</td><td>dense strength</td></tr><tr><td>Spongy bone</td><td>light honeycomb tissue</td></tr><tr><td>Marrow</td><td>blood cells / fat storage</td></tr><tr><td>Cartilage</td><td>smooth joint surface</td></tr><tr><td>Blood vessels</td><td>oxygen and nutrients</td></tr></table></section><section class="key-panel"><h3>Structure suits function</h3><p>Bone is not just solid material. Its layered structure gives strength without making the skeleton unnecessarily heavy.</p></section></div>`,[
        mcq("Which tissue reduces friction at bone ends?",["tendon","cartilage","marrow","periosteum"],1,"Cartilage provides a smooth surface at joints."),
        mcq("Which part provides dense strength?",["compact bone","marrow","blood vessel","cartilage"],0,"Compact bone is dense and strong.")
      ],2,["periosteum","cartilage","compact bone","spongy bone","marrow"]),
      lesson("Bone types, joints and connective tissues","Bone shape and connective tissues support different kinds of movement.",[
        "Long, short, flat and irregular bones have shapes suited to different functions.","Tendons connect muscle to bone; ligaments connect bone to bone.","Hinge joints mainly move in one plane; ball-and-socket joints move in many directions."
      ],`<div class="lesson-grid"><section class="note-panel"><h3>Bone types</h3><ul><li><strong>Long:</strong> femur, humerus — leverage and movement.</li><li><strong>Short:</strong> carpals — stability with small movements.</li><li><strong>Flat:</strong> skull — protection and broad muscle attachment.</li><li><strong>Irregular:</strong> vertebrae — specialised shapes.</li></ul></section><section class="note-panel"><h3>Connective tissues</h3><ul><li>Tendon: muscle → bone.</li><li>Ligament: bone → bone.</li><li>Cartilage: smooths joint surfaces.</li></ul></section><section class="worked-panel wide"><h3>Joint types</h3><p>Elbow/knee = hinge. Shoulder/hip = ball-and-socket.</p></section></div>`,[
        mcq("What connects muscle to bone?",["ligament","tendon","cartilage","marrow"],1,"Tendons attach muscle to bone."),
        mcq("The shoulder is mainly what type of joint?",["hinge","ball-and-socket","fixed","pivot only"],1,"The shoulder is a ball-and-socket joint.")
      ],3,["tendon","ligament","cartilage","hinge","ball-and-socket"]),
      lesson("Exercise and muscle fatigue","Repeated exercise changes performance and increases demands on body systems.",[
        "Working muscles need more energy, oxygen and glucose.","Breathing rate and heart rate increase during exercise.","Fatigue can reduce force, speed and movement control.","A fair fatigue investigation keeps technique and timing consistent."
      ],`<div class="lesson-grid"><section class="note-panel"><h3>During exercise</h3><p>Muscles use energy more rapidly. Ventilation and circulation increase to deliver oxygen and nutrients and remove carbon dioxide and heat.</p></section><section class="key-panel"><h3>Investigation thinking</h3><p>Use the same movement, interval length, technique and range of motion. Graph performance against time or set number and describe the pattern before explaining it.</p></section></div>`,[
        mcq("During exercise, breathing rate usually…",["decreases immediately","increases","stays exactly constant","stops"],1,"Ventilation increases to support greater metabolic demand."),
        mcq("For a fair fatigue test, which should stay consistent?",["technique and timing","participant every interval","the dependent variable","all results"],0,"Controls make the comparison fair.")
      ],4,["fatigue","exercise","oxygen","recovery"]),
      lesson("Breathing mechanics","Ventilation moves air into and out of the lungs by changing chest volume and pressure.",[
        "Inhaling: diaphragm contracts/flattens, ribs move up/out, chest volume increases and pressure decreases.","Exhaling: diaphragm relaxes/domes, ribs move down/in, chest volume decreases and pressure increases.","Air moves from higher pressure to lower pressure."
      ],`<div class="lesson-grid"><section class="note-panel"><h3>Breathing in</h3><ol class="worked-steps"><li>Diaphragm contracts and flattens.</li><li>Rib cage moves up and out.</li><li>Chest volume increases.</li><li>Pressure inside falls.</li><li>Air moves in.</li></ol></section><section class="note-panel"><h3>Breathing out</h3><ol class="worked-steps"><li>Diaphragm relaxes and domes.</li><li>Rib cage moves down and in.</li><li>Chest volume decreases.</li><li>Pressure inside rises.</li><li>Air moves out.</li></ol></section></div>`,[
        mcq("During inhalation, the diaphragm…",["relaxes and domes","contracts and flattens","does not move","contracts upward"],1,"Flattening increases chest volume."),
        mcq("When chest volume increases, pressure inside the lungs generally…",["increases","decreases","becomes 7","does not relate"],1,"Increasing volume lowers pressure and air moves in.")
      ],5,["ventilation","diaphragm","pressure","volume"]),
      lesson("Gas exchange and alveoli","Diffusion moves oxygen and carbon dioxide between alveoli and blood.",[
        "Oxygen diffuses from alveoli into blood; carbon dioxide diffuses from blood into alveoli.","Diffusion is movement from higher to lower concentration.","Alveoli are adapted with a large surface area, thin moist walls and a rich capillary supply."
      ],`<div class="lesson-grid"><section class="note-panel"><h3>At the alveoli</h3><div class="lungs-flow"><article><strong>ALVEOLUS</strong><p>more O₂<br>less CO₂</p></article><b>⇄</b><article><strong>BLOOD</strong><p>less O₂<br>more CO₂</p></article></div><p>Oxygen diffuses into blood while carbon dioxide diffuses into the alveolus to be exhaled.</p></section><section class="key-panel"><h3>Why alveoli are efficient</h3><ul><li>Many alveoli → very large surface area.</li><li>Walls one cell thick → short diffusion distance.</li><li>Moist surface → gases dissolve.</li><li>Dense capillary network → maintains concentration gradients.</li></ul></section></div>`,[
        mcq("Oxygen moves from alveoli into blood mainly by…",["diffusion","filtration","contraction","evaporation"],0,"Oxygen diffuses down its concentration gradient."),
        mcq("Why do alveoli have thin walls?",["to store more air","to shorten diffusion distance","to make mucus","to increase pressure"],1,"A short diffusion distance speeds gas exchange.")
      ],5,["alveoli","diffusion","oxygen","carbon dioxide","capillary"])
    ]
};