const checkpointLinks={forces:"",chemistry:"",body:""};
const storage={get(key,fallback){try{return JSON.parse(localStorage.getItem(key))??fallback}catch{return fallback}},set(key,value){try{localStorage.setItem(key,JSON.stringify(value))}catch{}}};

const practicals=[
{unit:"forces",title:"Tug of war",aim:"Observe balanced and unbalanced forces.",equipment:"Rope, centre marker, floor line.",method:["Set the rope marker over the centre line.","Pull with equal effort and observe the marker.","Change the number or effort on one side.","Draw free-body diagrams for both trials."],science:"Balanced forces give a net force of 0 N. An unbalanced net force causes acceleration.",safety:"Use a clear area, closed shoes and controlled pulling."},
{unit:"forces",title:"Sprint acceleration",aim:"Calculate speed over sections of a sprint and identify acceleration.",equipment:"Measured course, cones, stopwatches.",method:["Mark equal sections.","Record cumulative time at each marker.","Calculate speed for each section.","Compare speeds and identify where velocity changed."],science:"Acceleration occurs when velocity changes.",safety:"Check the surface, warm up and leave stopping distance."},
{unit:"forces",title:"Ramp investigation",aim:"Investigate how ramp angle affects motion.",equipment:"Ramp, trolley or ball, blocks, tape measure, stopwatch.",method:["Choose several ramp heights or angles.","Keep release point and travel distance the same.","Release without pushing and record time.","Repeat and calculate mean speed."],science:"A steeper ramp increases the component of gravity acting down the ramp, so acceleration usually increases.",safety:"Use a stop block and keep hands and feet clear."},
{unit:"chemistry",title:"Sherbet practical",aim:"Investigate how changing the mixture affects fizz.",equipment:"Approved food-grade sherbet ingredients, spoons, cups, measuring equipment.",method:["Use the class-approved base recipe.","Change one ingredient amount at a time.","Record fizz using the agreed method.","Link the fizz to carbon dioxide production."],science:"Citric acid and hydrogencarbonate react when dissolved, producing carbon dioxide gas.",safety:"Use only approved food-grade ingredients and clean equipment."},
{unit:"chemistry",title:"Household pH",aim:"Estimate pH of common solutions using universal indicator.",equipment:"Spotting tile, droppers, universal indicator, labelled solutions, pH chart.",method:["Place each solution in a separate well.","Add indicator.","Record colour.","Estimate pH and classify."],science:"Indicator colour provides an estimated pH and acid/neutral/alkali classification.",safety:"Wear goggles. Use clean droppers. Never taste laboratory samples."},
{unit:"chemistry",title:"Separating a mixture",aim:"Separate a mixture using physical properties.",equipment:"Magnet, beakers, water, filter funnel/paper, evaporating dish and approved heating equipment.",method:["Use magnetism if appropriate.","Dissolve any soluble component.","Filter insoluble material.","Evaporate or distil to recover dissolved substances/solvent."],science:"Each step uses a physical property such as magnetism, solubility, particle size or boiling point.",safety:"Wear goggles and handle hot equipment carefully."},
{unit:"body",title:"Muscle fatigue investigation",aim:"Measure how repeated exercise affects performance.",equipment:"Timer and a safe repeatable movement.",method:["Choose a fixed movement and clear success rule.","Record repetitions in equal intervals.","Continue for the agreed duration.","Graph results and describe the pattern."],science:"Repeated contraction uses energy and performance may decrease as fatigue develops.",safety:"Warm up and stop for pain, dizziness or poor technique."},
{unit:"body",title:"Chicken wing dissection",aim:"Identify muscles, tendons, ligaments, cartilage and joints in a real limb.",equipment:"Chicken wing, tray, gloves, goggles, scissors/scalpel, forceps.",method:["Inspect the outside and joint movement.","Open the skin carefully.","Pull selected muscles and observe movement.","Identify tendon, ligament and cartilage before disposal."],science:"Contracting muscles pull through tendons to move bones; ligaments stabilise joints and cartilage reduces friction.",safety:"Wear gloves/goggles, cut away from hands and disinfect surfaces."}
];
const practicalGuides={
"Tug of war":{iv:"Pulling force or team arrangement",dv:"Direction/change in motion",controls:"Same rope, surface, start line and pull time",results:"Record arrangement and marker movement.",graph:"Graph only if numerical data are collected.",conclusion:"Link net force to acceleration.",improvement:"Use force meters and repeats.",finish:"Two labelled free-body diagrams plus an explanation."},
"Sprint acceleration":{iv:"Distance section/time interval",dv:"Calculated speed",controls:"Same runner, course, start and timing method",results:"Record distance/time and calculate section speeds.",graph:"Plot section or time against speed.",conclusion:"Identify where velocity changed.",improvement:"Use video/light gates.",finish:"Calculations, graph and evidence-based description."},
"Ramp investigation":{iv:"Ramp height or angle",dv:"Travel time/speed",controls:"Same object, distance, surface and release",results:"Repeat times and calculate means.",graph:"Plot angle/height against mean speed.",conclusion:"Describe trend and link it to force down the ramp.",improvement:"Use a release gate/electronic timing.",finish:"At least four settings, means, graph and explanation."},
"Sherbet practical":{iv:"Amount/ratio of one ingredient",dv:"Agreed fizz measure",controls:"Other ingredient amounts and sample size",results:"Record recipe change and observation consistently.",graph:"Use a bar graph if the response was scored numerically.",conclusion:"Connect stronger fizz to gas production.",improvement:"Use measured masses and a consistent rating method.",finish:"Recipe table, observations and reaction explanation."},
"Household pH":{iv:"Solution tested",dv:"Indicator colour/estimated pH",controls:"Same sample volume, indicator drops and clean equipment",results:"Table sample, colour, pH and class.",graph:"A pH bar chart is optional.",conclusion:"Justify classifications with pH evidence.",improvement:"Repeat with pH paper/probe.",finish:"All approved samples recorded and classified."},
"Separating a mixture":{iv:"Separation step",dv:"Material recovered",controls:"Same starting mixture and careful transfer",results:"Record each recovered component.",graph:"Graph recovery only if masses are measured.",conclusion:"Explain each method using the property it exploits.",improvement:"Reduce transfer losses.",finish:"Recovered components plus justified method order."},
"Muscle fatigue investigation":{iv:"Exercise time/set",dv:"Successful reps/hold time",controls:"Same person, movement, technique, interval and recovery",results:"Record performance at equal intervals.",graph:"Time/set number vs performance.",conclusion:"Describe and explain the trend.",improvement:"Standardise range of motion and recovery.",finish:"Safe fair test, graph and evidence-based explanation."},
"Chicken wing dissection":{iv:"Anatomical observation",dv:"Identified structures/movement",controls:"Same dissection sequence and criteria",results:"Use a labelled diagram/table.",graph:"No graph required.",conclusion:"Explain how muscle, tendon, bone, ligament and cartilage work together.",improvement:"Use multiple views and careful tissue separation.",finish:"Labelled record connecting each structure to function."}
};

const revision={
forces:{cards:[["What is a force?","A push or pull measured in newtons (N)."],["Balanced forces give what net force?","0 N."],["What belongs on a free-body diagram?","External forces acting on the chosen object."],["State the speed equation.","speed = distance ÷ time"],["State the acceleration equation.","acceleration = change in velocity ÷ time"],["Distance–time gradient represents…","Speed."],["Speed–time gradient represents…","Acceleration."],["Horizontal on a distance–time graph means…","Stationary."],["Horizontal above zero on a speed–time graph means…","Constant speed."],["State the work equation.","work = force × distance"],["Unit of work?","Joule, J."],["Newton’s First Law is about…","Inertia and motion when net force is zero."],["State Newton’s Second Law.","F = ma."],["Newton’s Third Law pairs act on…","Different objects."],["If mass doubles at the same force, acceleration…","Halves."],["What should every calculation answer include?","Working and units."]],quiz:[]},
chemistry:{cards:[["Define an element.","One type of atom."],["Define a compound.","Different elements chemically bonded in a fixed ratio."],["Define a mixture.","Substances together without being chemically bonded."],["Describe gas particles.","Far apart and moving freely."],["Where are protons and neutrons?","In the nucleus."],["Charge of an electron?","−1."],["Atomic number tells us…","Number of protons."],["Electron arrangement of sodium?","2,8,1."],["Symbol for magnesium?","Mg."],["What is a group?","A vertical periodic-table column."],["What is a period?","A horizontal row."],["Neutral pH?","7."],["Purple universal indicator suggests…","Alkaline."],["What gas makes sherbet fizz?","Carbon dioxide."],["Filtration separates…","An insoluble solid from a liquid."],["Distillation can recover…","A solvent/liquid from a solution."],["Why pencil in chromatography?","Graphite does not dissolve and travel like ink."],["Where should chromatography spots sit?","Above the solvent level."]],quiz:[]},
body:{cards:[["Name the three muscle types.","Skeletal, smooth and cardiac."],["What does a tendon connect?","Muscle to bone."],["What does a ligament connect?","Bone to bone."],["During elbow flexion…","Biceps contracts; triceps relaxes."],["During elbow extension…","Triceps contracts; biceps relaxes."],["Main role of cartilage at joints?","Reduce friction."],["What does compact bone provide?","Dense strength."],["What is periosteum?","The tough outer membrane involved in blood supply and repair."],["Where are blood cells produced?","Bone marrow."],["Example of a hinge joint?","Elbow or knee."],["Example of a ball-and-socket joint?","Shoulder or hip."],["What happens to the diaphragm during inhalation?","It contracts and flattens."],["What happens to chest volume during inhalation?","It increases."],["Where does gas exchange occur?","Across alveolar and capillary walls."],["Direction of oxygen diffusion?","Alveoli into blood."],["Direction of carbon dioxide diffusion?","Blood into alveoli."],["Give two alveolus adaptations.","Large surface area, thin moist walls, rich blood supply; any two."]],quiz:[]}
};
revision.forces.quiz=[mcq("80 N right and 35 N left gives…",["45 N right","45 N left","115 N right","0 N"],0,"80−35=45 N right."),mcq("150 m in 30 s gives…",["4 m/s","5 m/s","30 m/s","180 m/s"],1,"150÷30=5 m/s."),mcq("Distance–time horizontal section means…",["accelerating","stationary","returning","constant acceleration"],1,"Distance is unchanged."),mcq("Speed rises 4 to 16 m/s in 6 s. Acceleration?",["2 m/s²","3 m/s²","12 m/s²","20 m/s²"],0,"(16−4)÷6=2."),mcq("40 N over 6 m gives work of…",["46 J","240 J","6.7 J","400 J"],1,"W=Fd=240 J."),mcq("3 kg at 4 m/s² needs…",["0.75 N","7 N","12 N","24 N"],2,"F=ma=12 N."),mcq("Third Law pair?",["weight/support on one book","foot pushes ground; ground pushes foot","engine/drag on one car","two forces on one rope"],1,"They act on different objects."),mcq("Speed–time gradient gives…",["speed","distance","acceleration","work"],2,"Gradient is acceleration."),mcq("If net force is zero, a moving object can…",["continue at constant velocity","only stop","only speed up","only turn"],0,"Zero net force means zero acceleration."),mcq("Same force on twice the mass gives acceleration that…",["doubles","halves","stays the same","becomes negative"],1,"a=F/m."),mcq("Equation for distance?",["v÷t","v×t","t÷v","F×d"],1,"d=vt."),mcq("Acceleration unit?",["m/s","m/s²","J","N"],1,"m/s².")];
revision.chemistry.quiz=[mcq("Which is a compound?",["air","gold","water","oxygen"],2,"Water contains bonded H and O."),mcq("Gas particles are…",["fixed","far apart and moving freely","all in the nucleus","stationary"],1,"Gas particles are widely spaced."),mcq("Negative particle?",["proton","neutron","electron","nucleus"],2,"Electron charge is −1."),mcq("Mg electron arrangement?",["2,10","2,8,2","8,4","2,8,8"],1,"12 electrons → 2,8,2."),mcq("Vertical periodic-table column?",["period","group","shell","compound"],1,"Columns are groups."),mcq("pH 3 is…",["acidic","neutral","alkaline","metallic"],0,"Below 7 is acidic."),mcq("Purple universal indicator is…",["acidic","neutral","alkaline","colourless"],2,"Purple is alkaline."),mcq("Sherbet fizz gas?",["oxygen","hydrogen","carbon dioxide","nitrogen"],2,"The reaction produces CO₂."),mcq("Filtration separates…",["dissolved salt from water","insoluble solid from liquid","two gases","atoms from molecules"],1,"The filter traps insoluble solids."),mcq("Recover water from salt solution using…",["filtration","magnetism","distillation","chromatography"],2,"Distillation boils and condenses water."),mcq("Chromatography baseline should use…",["ink","pencil","paint","marker"],1,"Graphite does not travel like ink."),mcq("Atomic number equals number of…",["protons","neutrons","shells","compounds"],0,"Proton number defines the element.")];
revision.body.quiz=[mcq("Heart-only muscle?",["skeletal","smooth","cardiac","voluntary"],2,"Cardiac muscle."),mcq("Muscle to bone?",["ligament","tendon","cartilage","marrow"],1,"Tendon."),mcq("Elbow extension contracts…",["biceps","triceps","deltoid","quadriceps"],1,"Triceps."),mcq("Reduces friction at bone ends?",["tendon","cartilage","marrow","periosteum"],1,"Cartilage."),mcq("Blood cells are produced in…",["tendons","marrow","ligaments","cartilage"],1,"Bone marrow."),mcq("Shoulder joint type?",["hinge","ball-and-socket","fixed","suture"],1,"Ball-and-socket."),mcq("During inhalation diaphragm…",["relaxes and domes","contracts and flattens","does not move","contracts upward"],1,"It contracts and flattens."),mcq("Chest volume during inhalation…",["decreases","stays fixed","increases","becomes zero"],2,"It increases."),mcq("Oxygen enters blood by…",["diffusion","filtration","contraction","evaporation"],0,"Diffusion."),mcq("Thin alveolar walls…",["store air","shorten diffusion distance","increase friction","make blood"],1,"They shorten diffusion distance."),mcq("Back of thigh muscle group?",["quadriceps","hamstrings","pectorals","biceps"],1,"Hamstrings."),mcq("Ligaments connect…",["muscle to bone","bone to bone","skin to muscle","blood to alveoli"],1,"Bone to bone.")];
const writtenPractice=[
{unit:"Forces & Motion",q:"Describe a free-body diagram for a book resting on a table and explain why it does not accelerate.",a:"Weight acts downward and support/normal force acts upward with equal size. Net force is 0 N, so acceleration is zero."},
{unit:"Forces & Motion",q:"A cyclist changes from 3 m/s to 15 m/s in 4 s. Calculate acceleration and show working.",a:"a=(15−3)÷4=3 m/s²."},
{unit:"Chemistry",q:"Explain how you would separate iron filings, sand and salt.",a:"Use a magnet for iron. Add water to dissolve salt. Filter out sand. Evaporate or distil the filtrate to recover salt (and water if distilling)."},
{unit:"Chemistry",q:"Explain why a chromatography spot must start above the solvent level.",a:"Otherwise the sample dissolves into the solvent reservoir instead of travelling up the paper with the solvent front."},
{unit:"Body Systems",q:"Explain elbow flexion using biceps, triceps, contracts and relaxes.",a:"The biceps contracts and shortens while the triceps relaxes and lengthens, pulling the forearm upward."},
{unit:"Body Systems",q:"Explain two alveolus adaptations and how each improves gas exchange.",a:"Examples: large surface area, thin walls, moist surface and rich blood supply; explain how each increases diffusion rate."}
];
const examQuestions=[...revision.forces.quiz.slice(0,8),...revision.chemistry.quiz.slice(0,8),...revision.body.quiz.slice(0,8)];
let currentTerm="forces",currentLesson=0,revisionMode="cards",cardIndex=0;